FROM node:20-slim

WORKDIR /app

COPY pdfWorker/package*.json ./
COPY pdfWorker/tsconfig.json ./
COPY pdfWorker/fonts ./fonts
COPY pdfs ./pdfs

RUN npm install

COPY pdfWorker/src/ ./src/

RUN npm run build

CMD ["npm", "start"]