services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./apiOficios
    ports:
      - "3333:3333"
    env_file:
      - ./apiOficios/.env

  pdfWorker:
    build: ./pdfWorker
    env_file:
      - ./pdfWorker/.env
    depends_on:
      - rabbitmq:
        condition: service_healthy

  emailWorker:
    build: ./emailWorker
    env_file:
      - ./emailWorker/.env
    depends_on:
      - rabbitmq:
        condition: service_healthy
