FROM node:20-alpine

WORKDIR /app

COPY emailWorker/package*.json ./
COPY emailWorker/tsconfig.json ./
COPY pdfs ./pdfs

RUN npm install

COPY emailWorker/src ./src

RUN npm run build

CMD ["npm", "start"]