FROM node:20-alpine

WORKDIR /app

COPY apiOficios/package*.json ./
COPY apiOficios/tsconfig.json ./

RUN npm install

COPY apiOficios/src/ ./src/

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]